spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://104.248.47.45:5433/bookstorage
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog.yml
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

logging:
  level:
    web: TRACE